### ISSUE TITLE
Super Secret Settings causes gray around crosshair

### ISSUE THREAD

**Issue by fineless71** [dracula/minecraft#14]
I'm on 1.7.10. This is a strange one, and it really doesn't matter so close it if you're not bothered. Using _any_ of the super secret settings causes a gray box around the crosshair. The perhaps weird part is it doesn't affect OptiFine shaders. I couldn't reproduce this on any other resource pack.
![image](https://github.com/dracula/minecraft/assets/118756680/1f11f1df-0890-4720-87aa-40ceccc6a247)

**Comment by fineless71** [comment]
I just tested and this affects the motion blur mod so I think it matters a bit more now

**Comment by Zentheon** [comment]
Definitely an odd one. Quick testing suggests it's isolated to `icons.png`, whatever it is. Will check it out more tomorrow

**Comment by Zentheon** [comment]
Fixed in Beta 3. Turns out after some web searching, the game actually considered fully black pixels to be transparent. So, even if background pixels are completely transparent, if the underlying RGB value is white it'll still register, like a lot of graphical programs do. Simple fix was to just add a black background since all versions of the game treat black the same way.

Not sure why it triggers randomly on 1.7.10 through; I feel like it happened at least once without even touching the post processing effects button.
