### ISSUE TITLE
Broken creative menu on 1.19.3

### ISSUE THREAD

**Issue by scanbash** [dracula/minecraft#6]
The interface is absolutely gorgeous with this pack, but it seems the creative menu has been changed in the latest MC update. Hope it's not too much trouble to fix!

Thank you for the resource pack!

![dracula_gui_issue](https://user-images.githubusercontent.com/118480064/212522402-2bd80673-56f6-4393-8b89-00b47c9dc710.png)

**Comment by Zentheon** [comment]
Oh weird! An update like that usually doesn't break something, will look into it.

**Comment by Zentheon** [comment]
As it turns out, the tabs texture has been changed from 1.19.2 to 1.19.3 to fit the new layout. Unfortunately, the file for that texture uses the same name, essentially nuking backwards compatibility. Mojang is really inconsistent about this since sometimes they use new names and sometimes not.

Anyway this is far from ideal since the pack's structure heavily relies on just being a "one version fits all."

**Comment by Zentheon** [comment]
For now the only way to have working tabs is to use an addon, which I've now uploaded to Modrinth

https://modrinth.com/resourcepack/dracula-theme/version/AF-2

**Comment by scanbash** [comment]
> For now the only way to have working tabs is to use an addon, which I've now uploaded to Modrinth
> 
> https://modrinth.com/resourcepack/dracula-theme/version/AF-2

Works great! Thank you!
